//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietMenu.Resources.Queries {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DietMenu.Resources.Queries.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select 1
        ///from users
        ///where user_login = @login.
        /// </summary>
        internal static string CheckLoginExistence {
            get {
                return ResourceManager.GetString("CheckLoginExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert into resources
        ///(
        /// resource_type_id,
        /// resource_path
        ///)
        ///values
        ///(
        /// 2,
        /// @path
        ///).
        /// </summary>
        internal static string CreateImage {
            get {
                return ResourceManager.GetString("CreateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert into users
        ///(
        /// user_login,
        /// user_hash,
        /// user_name,
        /// user_surname,
        /// user_height,
        /// user_weight,
        /// user_age,
        /// user_gender_type_id,
        /// user_type_id
        ///)
        ///values
        ///(
        /// @login,
        /// @hash,
        /// @name,
        /// @surname,
        /// @height, 
        /// @weight,
        /// @age,
        /// @genderid,
        /// 1
        ///).
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select food.ingestion_name as Трапеза,
        ///       food.dish_name as Блюдо,
        ///       round(sum(food.proteins)) as Белков,
        ///       round(sum(food.fats)) as Жиров ,
        ///       round(sum(food.carbohydrates)) as Углеводов,
        ///       round(sum(food.calories)) as Калорий
        ///from
        ///
        ///    (
        ///	 select it.ingestion_type_name as ingestion_name,
        ///            d.dish_name as dish_name,
        ///            p.proteins * pld.product_proportion * es.portion as proteins,
        ///            p.fats * pld.product_proportion * es.portion as fats,
        ///        [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetActualUserMenu {
            get {
                return ResourceManager.GetString("GetActualUserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select food.dish_name as Блюдо,
        ///       round(sum(food.proteins)) as Белки,
        ///       round(sum(food.fats)) as Жиры ,
        ///       round(sum(food.carbohydrates)) as Углеводы,
        ///       round(sum(food.calories)) as Калории
        ///from
        ///
        ///    (
        ///	 select it.ingestion_type_name as ingestion_name,
        ///            d.dish_name as dish_name,
        ///            p.proteins * pld.product_proportion * es.portion as proteins,
        ///            p.fats * pld.product_proportion * es.portion as fats,
        ///            p.carbohydrates * pld.product_proporti [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetDishes {
            get {
                return ResourceManager.GetString("GetDishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select product_name as Название,
        ///	   proteins as Белки,
        ///	   fats as Жиры,
        ///	   carbohydrates as Углеводы,
        ///	   calories as Калории
        ///from products.
        /// </summary>
        internal static string GetProducts {
            get {
                return ResourceManager.GetString("GetProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select user_id as Id,
        ///	   user_login as Login,
        ///	   user_hash as Hash,
        ///	   user_name as Name,
        ///	   user_surname as Surname,
        ///	   user_height as Height,
        ///	   user_weight as Weight,
        ///	   user_age as Age,
        ///	   user_gender_type_id as GenderId,
        ///	   user_type_id as TypeId,
        ///	   entity_id as EntityId
        ///from users
        ///where user_login = @login.
        /// </summary>
        internal static string GetUser {
            get {
                return ResourceManager.GetString("GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select user_gender_type_id as GenderId,
        ///       user_gender_type_name as GenderName
        ///from user_gender_types.
        /// </summary>
        internal static string GetUserGenderTypes {
            get {
                return ResourceManager.GetString("GetUserGenderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select r.resource_path
        ///from resource_link_entity rle,
        ///	 resources r
        ///where rle.entity_id = @entityid
        ///  and r.resource_id = rle.resource_id
        ///  and r.resource_type_id = 2
        /// .
        /// </summary>
        internal static string GetUserImagePath {
            get {
                return ResourceManager.GetString("GetUserImagePath", resourceCulture);
            }
        }
    }
}
